### ISSUE TITLE
Julia language support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-syntax#23]
Implement optimized styles for <img src="http://julialang.org/favicon.ico" width=16 height=16/> [Julia](http://julialang.org) entities for the [milestone backlog](https://github.com/arcticicestudio/nord-atom-syntax/issues/1) community :package: package <img src="https://avatars2.githubusercontent.com/u/743164" width=16 height=16/> [`language-julia`](https://atom.io/packages/language-julia) by [JuliaLang](https://github.com/JuliaLang)
1. Macros should be colored correctly

**Comment by arcticicestudio** [comment]
Implemented in the referenced commits. Merged in 61eec2ca99fa5018d1f9f67980bb24a8e114ba1d.

**Comment by deszoeke** [comment]
Multiline strings
```
"""
stringy
stringier
stringiest
"""
```
are not highlighted in the same color as strings.

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 
Have you tried to use the correct indentation? ([heredoc](https://en.wikipedia.org/wiki/Here_document))

![ghi-23-scrot-indentation](https://cloud.githubusercontent.com/assets/7836623/24771155/caef5738-1b0c-11e7-8914-d93e0a117535.png)

**Comment by deszoeke** [comment]
I have never seen that indentation for docstrings.

**Comment by arcticicestudio** [comment]
I've debugged with the `langauge-julia` package and found out that it makes use of the `.source--gfm` (GitHub Flavored Markdown` selector for multiline strings. It adapts the default text color of it which is `nord4`.
This seems to lead to problems more often which can be seen by the amount of issues in the `language-julia` repository related to this problem.

Anyway, I'll create a new ticket to fix this for the Nord Atom Syntax theme and add a @-mention so you can test the changes.
