### ISSUE TITLE
Elixir language support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-syntax#33]
Implement optimized <img src="http://elixir-lang.org/favicon.ico" width=16 height=16/> [Elixir](http://elixir-lang.org) styles for the [milestone backlog](https://github.com/arcticicestudio/nord-atom-syntax/issues/1) community :package: package <img src="https://avatars0.githubusercontent.com/u/1481354" width=16 height=16/>  [`language-elixir`](https://atom.io/packages/language-elixir) by [elixir-lang](https://github.com/elixir-lang)

  1. Use annotation color for `.module` CSS class and the associated punctuation definition symbol
  2. Use class color for `.constant` CSS class

Requested by @skbolton in the [backlog milestone issue](https://github.com/arcticicestudio/nord-atom-syntax/issues/1#issuecomment-267854982).

**Comment by arcticicestudio** [comment]
@skbolton These are the style optimizations I've implemented so far.
You can test it by installing the [`language-elixir`](https://atom.io/packages/language-elixir) package and check out the [`ghi-#33-elixir-language-support`](https://github.com/arcticicestudio/nord-atom-syntax/tree/feature/ghi-%2333-elixir-language-support) branch.

Feel free to suggest improvements/additions 😄 🎅

**Comment by skbolton** [comment]
Will definitely play with it over the holiday break. I love that color for the annotations, I was going to use the same one from the color palette. Really nice

**Comment by skbolton** [comment]
Yeah I really like the addition of the rust color for annotations. Now I just wish I could get more of that color in my js highlighting :)

**Comment by arcticicestudio** [comment]
I'll merge this and prepare a new release version in the next days.
Do you mean ES6 decorators like `@readonly`?

**Comment by arcticicestudio** [comment]
🚢 Shipped in apm package release version [0.5.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.5.0).
