### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MaximSokolov** [arcticicestudio/nord-atom-syntax#36]
:memo: __A__ arctic syntax theme -> __An__ arctic syntax theme

**Comment by arcticicestudio** [comment]
Thanks for your report 👍
Someone has already pointed out to me, but I've pushed it out of my mind due to the fact that I've to update all port projects 😆 
I'll get into it as soon as I've got some freetime.

**Comment by arcticicestudio** [comment]
➡️ Move this issue to the main project repository [nord #20](https://github.com/arcticicestudio/nord/issues/20).
