### ISSUE TITLE
default indent guide is too bright

### ISSUE THREAD

**Issue by smokebacon** [arcticicestudio/nord-atom-syntax#43]
![image](https://cloud.githubusercontent.com/assets/18046018/24534148/d0134f16-1617-11e7-927e-519e05737a96.png)

It's actually brighter than comments color in default state which is not ideal when you have comments being outshine by the indent guide itself. I suggest darken the making guides to nord2.

**Comment by arcticicestudio** [comment]
I've tested it and agree that `@nord2` looks more unobstructive since it is meant to be used for such UI elements anyway 👍

**Comment by arcticicestudio** [comment]
<p align="center"><strong>Before</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/24577138/9b9addf6-16c8-11e7-9f9e-b044bf6e89b4.png"/><br><strong>After</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/24577141/a6c329fe-16c8-11e7-810f-ab267d8a0c96.png"/></p>

<p align="center"><strong><a href="https://github.com/arcticicestudio/nord-atom-ui/issues/64">Nord Atom UI #64</a> preview</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/24577073/8a3486da-16c7-11e7-83a7-40cceaa7c87c.gif"/></p>

**Comment by arcticicestudio** [comment]
🚢 Shipped in APM 📦 package release version 🏷  [0.7.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.7.0).

/cc @smokebacon
