### ISSUE TITLE
Laravel Blade Support

### ISSUE THREAD

**Issue by whereisjefe** [arcticicestudio/nord-atom-syntax#44]
First off love this theme, looks great and i really want to make this my default theme... However one small issue...

Any chance we could get https://atom.io/packages/language-blade support?

Thanks

**Comment by arcticicestudio** [comment]
Thanks, nice to see you like it 😄 
Sure, added it to the backlog.

**Comment by arcticicestudio** [comment]
I've pushed the initial implementation.
You can test it by checking out 🌱 [feature/ghi-#44-laravel-blade-support](https://github.com/arcticicestudio/nord-atom-syntax/tree/feature/ghi-%2344-laravel-blade-support)

The language specific keywords are colorized with `@syntax-color-annotation` which also fits perfect to the theme color of the Laravel framework.

<p align="center"><strong>Laravel Blade Preview</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/24770330/db497b3e-1b09-11e7-958b-6f24641207e9.png"/></p>

**Comment by whereisjefe** [comment]
wow that was fast, thanks.

Just cloned repo and it is working perfectly, much easier for me to use now. Thanks again!

**Comment by arcticicestudio** [comment]
🚢 Shipped in APM package release version 🏷 [0.8.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.8.0).
