### ISSUE TITLE
Syntax highlighting in JSX

### ISSUE THREAD

**Issue by haveanicedavid** [arcticicestudio/nord-atom-syntax#50]
Currently, HTML tags within JSX don't currently format text in-between the tabs as white (as it does in normal HTML). Tags are rendered the same color as their content:
![screenshot 2017-07-07 15 46 45](https://user-images.githubusercontent.com/9052511/27978230-7fd2c624-632b-11e7-8f2b-dcf5a3fe3425.png)

vs Normal HTML: 
![screenshot 2017-07-07 15 48 43](https://user-images.githubusercontent.com/9052511/27978280-c6e959ba-632b-11e7-8dc7-e92d7cf0f70b.png)

It's an easy fix locally by adding the following to my stylesheet: 
```
.syntax--meta.syntax--tag {
    color: #d8dee9;
}
```
Love the theme!

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 

<p align="center">Before<br><img src="https://user-images.githubusercontent.com/7836623/27985204-5b5f7c30-63e7-11e7-9e50-b16915de2781.png"/><br>After<br><img src="https://user-images.githubusercontent.com/7836623/27985206-6894cb12-63e7-11e7-857b-98f727a1df50.png"/></p>
