### ISSUE TITLE
Closing PHP Tag ? Incorrectly Highlighted

### ISSUE THREAD

**Issue by amayer5125** [arcticicestudio/nord-atom-syntax#54]
The ? inherits `.syntax--source` coloring. It should use the `.syntax--punctuation.syntax--section.syntax--embedded` coloring. It is the same whether on its own line or in line.

![image](https://user-images.githubusercontent.com/3212673/31280678-21a9d1ae-aa7b-11e7-9842-20e6ad0500d9.png)

Atom Version: 1.12.0

**Comment by arcticicestudio** [comment]
Thanks for you report :+1: 

I'll review your PR as soon as possible. I'm not aware of any general syntax highlighting changes in Atom 1.20+, but I might check the merged PRs again to see if there are changes for closing tags as it seems to be similar to #52.
