### ISSUE TITLE
Are you ready to release a new version

### ISSUE THREAD

**Issue by linjialiang** [arcticicestudio/nord-atom-syntax#62]
Are you ready to release a new version

**Comment by arcticicestudio** [comment]
The next version will be [0.10.0](https://github.com/arcticicestudio/nord-atom-syntax/projects/13), but it relies on https://github.com/arcticicestudio/nord/issues/94 to be released with all other affected port projects.
As soon as the comment color brightness change has been adapted by the other port projects are  will be a blog post about the new comment color brightness

**Comment by linjialiang** [comment]
ok
